version: "3.7"
services:
  server:
    build:
      args:
      - NODE_ENV=development
      context: server
    command: npm run start-watch
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
    ports:
      - 5000:5000
      - 9229:9229
      - 9230:9230
    volumes:
      - ./server/src:/code/src:ro
      - ./server/package.json:/code/package.json
      - ./server/package-lock.json:/code/package-lock.json
      - back-fordebug:/opt/app/node_modules
  client:
    build:
      context: client
      target: development
    environment: 
      - REACT_APP_API_PORT=5000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/code/src
      - /code/node_modules
    depends_on:
      - server
volumes:
  back-fordebug:
